import { FormEvent, useState } from 'react'
import './App.css'
import { useQuery } from 'react-query';

// Generated by https://quicktype.io

export interface Post {
  userId: number;
  id:     number;
  title:  string;
  body:   string;
}



function App() {
  
  const [searchTerm, setSearchTerm] = useState('lorem');
  
  
  const getPosts = async(searchTerm: string) => {
    const resp = await fetch(`https://jsonplaceholder.typicode.com/posts?body_like=${searchTerm}`);
    const data = await resp.json();
  
    console.log(resp);
    
  
    return data;
  }

  const { data, isError, isLoading } = useQuery<Post[], Error>('posts', () => getPosts(searchTerm), {
    enabled: searchTerm !== ''
  })

  if(isLoading){
    return (
      <div className='spinner__container'>
          <div className='spinner'/>
      </div>
    )
  }

  if( isError ){
    return <span>Error.</span>
  }

  const onSubmit = (e: FormEvent) => {
    e.preventDefault();
    console.log(searchTerm);
  }

  const posts = searchTerm ? data?.filter(post => post.body.includes(searchTerm)) : data;



  return (
    <div>
      <h1 className='app__title'>Welcome to JSONPlaceHolder filter</h1>
      <form onSubmit={onSubmit} className='form__container'>
        <input 
          type="text" 
          onChange={(e) => setSearchTerm(e.target.value)} 
          name="text"
          value={searchTerm}
          className='form__input'
          autoFocus
        />

        <input 
          type="reset" 
          value="Reset" 
          onClick={() => setSearchTerm('')}
          className='form__reset'
        />
  
      </form>


      <div className='container'>
        {
          posts?.map(post => (
            <div key={post.id} className='card__container'>
              <h2 className='card__title'>{post.title}</h2>
              <p className='card__body'>{post.body}</p>

              <div className='card__wrap'>
                <p className='card__id'><strong>ID: </strong>{post.id}</p>
                <p className='card__id'><strong>USER ID: </strong>{post.userId}</p>
              </div>
              
            </div>
          ))
        }
      </div>
    </div>
  )
}

export default App
